### ISSUE TITLE
Filter menu

### ISSUE THREAD

**Issue by anonimo82** [crazii/fba4dstwo#5]
Is it there any way to filter rom menu, by just listing confirmed/working ones?
Thanks in advance for any help

**Comment by anonimo82** [comment]
@crazii ?

**Comment by anonimo82** [comment]
Also, some way to list each game uniquely would be useful (eg, list "street fighter" just once)

**Comment by crazii** [comment]
Sorry It's kinda out of maintenance now, if you're interested in improving it, any pull requests are welcomed.
Currently what you can do is to remove the non-working roms from the folder. 🤣

**Comment by anonimo82** [comment]
LOL already did it.
I guess we should close this, should us?
